apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: v2-api-apikey-ratelimit
spec:
  name: "v2 API Key rate limit"
  contextRef: 
    name: "management-context-1"
    namespace: "default"
  version: "1.0"
  description: "v2 API with API Key plan and rate limit"
  plans:
    - name: "KEY_LESS"
      description: "FREE"
      security: "KEY_LESS"
      flows:
        - name: ""
          path-operator:
            path: "/"
            operator: "STARTS_WITH"
          pre:
            - name: "spike-arrest"
              description: "spike-arrest"
              enabled: true
              policy: "spike-arrest"
              configuration:
                async: false
                addHeaders: false
                spike:
                  dynamicLimit: "20"
                  periodTime: 1
                  limit: 10
                  periodTimeUnit: "SECONDS"
                  key: "test"
          post: []
          enabled: true
      comment_required: false
  proxy:
    virtual_hosts:
      - path: "/v2-api-apikey-ratelimit"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
  local: false
