apiVersion: gravitee.io/v1alpha1
kind: Application
metadata:
  name: application-1
spec:
  contextRef:
    name: "management-context-1"
    namespace: "default"
  name: "My Kubernetes Application 1"
  type: "WEB"
  domain: "https://example.com"
  description: "Application created using GKO"
  metadata:
    - name: "test metadata"
      format: "STRING"
    - name: "test metadata 2"
      format: "STRING"