apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: echo-api-declarative
spec:
  name: "Echo API Declarative"
  contextRef: 
    name: "management-context-1"
    namespace: "default"
  version: "1"
  categories: ["cat1", "cat2"]
  state: STOPPED
  lifecycle_state: "PUBLISHED"
  description: "This is an API created by the Gravitee Kubernetes Operator"
  visibility: PUBLIC
  plans:
    - name: "KEY_LESS"
      description: "FREE"
      security: "KEY_LESS"
  proxy:
    virtual_hosts:
      - path: "/echo-declarative"
    groups:
      - endpoints:
          - name: "Default"
            target: "http://gravitee-echo-api.gravitee.svc.cluster.local:80"
  local: false
  # notifyMembers: true