apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: api-with-swagger-http-fetcher
spec:
  contextRef:
    name: management-context-1
    namespace: default
  name: "api-with-swagger-http-fetcher"
  version: "1.0"
  description: "An API with a swagger page fetched from HTTP"
  plans:
    - name: "KEY_LESS"
      description: "FREE"
      security: "KEY_LESS"
  proxy:
    virtual_hosts:
      - path: "/api-with-swagger-http-fetcher"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
  pages:
    swagger:
      name: "pet-store"
      type: SWAGGER
      source:
        type: 'http-fetcher'
        configuration:
          url: https://petstore.swagger.io/v2/swagger.json
          # autoFetch: true
          # fetchCron: '*/10 * * * * *'