apiVersion: gravitee.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
spec:
  contextRef:
    name: {{ .Values.context_name }}
  name: "K8s OAuth consumer app"
  description: "This app is used to consume JWT secured APIs"
  settings:
    oauth:
      applicationType: BACKEND_TO_BACKEND
      grantTypes:
        - "client_credentials"