apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: v2-api-apikey-ratelimit
spec:
  name: "v2 API Key rate limit"
  contextRef: 
    name: context
  version: "1.0"
  state: "STOPPED"
  lifecycle_state: "UNPUBLISHED"
  visibility: PUBLIC
  description: "Updated descritpion"
  plans:
    - name: "KEY_LESS"
      description: "FREE"
      security: "KEY_LESS"
      flows:
        - name: ""
          path-operator:
            path: "/"
            operator: "STARTS_WITH"
          pre:
            - name: "spike-arrest"
              description: "spike-arrest"
              enabled: true
              policy: "spike-arrest"
              configuration:
                async: false
                addHeaders: false
                spike:
                  dynamicLimit: "20"
                  periodTime: 1
                  limit: 10
                  periodTimeUnit: "SECONDS"
                  key: "test"
          post: []
          enabled: true
      comment_required: false
  proxy:
    virtual_hosts:
      - path: "/v2-api-apikey-ratelimit"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
  local: false
  metadata:
  - key: "build-version"
    name: "build-version"
    format: "STRING"
    value: "0.0.1"
  pages:
    markdowns-folder:
      name: markdowns
      type: FOLDER  
    markdown:
      name: "hello-markdown"
      type: MARKDOWN
      parent: markdowns-folder
      content: |
        Hello world!
        --
        This is markdown.
